name: SoundFix_Music_Player
description: A Music PLAYER APP FOR CREATIVES AND USERS.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1   # Remove the quotes and the colon, and make sure the version is in the correct format

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.0.5
  sleek_circular_slider: ^2.0.1
  palette_generator: ^0.3.3+2
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
